
services:  
  ms-client:
    build: .\ms-client
    image: amigoprogramador/msclient:latest
    container_name: amigoprogramador-msclient
    ports:
      - 8081:8081
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - amigoprogramador

  ms-debitcard:
    build: .\ms-debitcard
    image: amigoprogramador/msdebitcard:latest
    container_name: amigoprogramador-msdebitcard
    ports:
      - 8082:8082
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - amigoprogramador
  
  ms-transaction:
    build: .\ms-transaction
    image: amigoprogramador/mstransaction:latest
    container_name: amigoprogramador-mstransaction
    ports:
      - 8083:8083
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - amigoprogramador

  api-gateway:
    build: .\api-gateway
    image: amigoprogramador/apigateway:latest
    container_name: amigoprogramador-apigateway
    ports:
      - 9999:9999
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks:
      - amigoprogramador  

  config-server:
    build: .\config-server
    image: amigoprogramador/config-server:latest
    container_name: amigoprogramador-configserver
    ports:
      - 8888:8888
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
        interval: 10s
        retries: 3
        start_period: 10s
    networks:
      - amigoprogramador   

  mongodb:
    image: mongo:latest
    container_name: amigoprogramador-mongodb
    ports:
      - 27017:27017      
    networks:
      - amigoprogramador
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: amigoprogramador-zookeeper
    restart: always
    ports:
      - 2181:2181
    networks:
      - amigoprogramador
      
  kafka:
    image: wurstmeister/kafka
    container_name: amigoprogramador-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=TRANSFERENCE:1:1
      - KAFKA_BROKER_ID=1
    networks:
      - amigoprogramador 

networks:
  amigoprogramador:
