name: Mi Primer Workflow

on:
  push:
    branches: [ "feature/cicd-example" ]

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "¡Hola desde GitHub Actions!"